cursor #e6f0ff
cursor_text_color #ffffff

foreground            #e6f0ff
background            #000000
selection_foreground  #000000
selection_background  #999999
url_color             #03fcc6

color0   #000000
color1   #ff5500
color2   #02fc12
color3   #ffea00
color4   #00efbb
color5   #00745b
color6   #03fcc6
color7   #e0fff8
color8   #8ba39e
color9   #ff8142
color10  #4eff59
color11  #fff04e
color12  #28ffd0
color13  #4effd8
color14  #8dffe6
color15  #f2fffc
