#!/bin/bash

cd "$HOME" || exit

# Setup manual package dir
mkdir ~/Projects/Packages -p

echo "installing build tools"
pacman -S git make unzip gcc base-devel

echo "cloning paru"
git clone https://aur.archlinux.org/paru.git ~/Packages/paru
cd ~/Projects/Packages/paru || exit
makepkg -si

# # Install software
# paru -S --needed - <~/.config/yadm/packages.txt
# # Install drivers
# paru -S --needed - <~/.config/yadm/drivers.txt

# Setup systemd services
systemctl enable --user hypaper
sudo systemctl enable sshd
