windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = floating-screenshots
    match:class = be.alexandervanhee.gradia
    float = yes
}

windowrule {
    name = float-inputpicker
    match:class = hyprland-share-picker
    float = yes
}

# Scribe hide, hides whole screen
# layerrule {
#     name = hide-scribe-tools
#     match:namespace = ^wayscriber*
#     no_screen_share = true
# }

windowrule {
    name = matrix-on-magic
    match:class = org.gnome.Fractal
    workspace = special:magic
}

windowrule {
    name = evolution
    match:class = org.gnome.Evolution
    workspace = special:magic
}

windowrule {
    name = zoom-on-magic
    match:class = zoom
    workspace = special:magic
}

windowrule {
    name = discord-on-magic
    match:class = discord
    workspace = special:magic
}

windowrule {
    name = equibop-on-magic
    match:class = equibop
    workspace = special:magic
}
